name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Auto-format with Black
      run: |
        black . --line-length 88

    - name: Generate data
      run: |
        python data_creator.py

    - name: Train model
      run: |
        python model_trainer.py

    - name: Run tests
      run: |
        PYTHONPATH=$PWD pytest
